eturnal:
  secret: tiredofit
  relay_min_port: 49152
  relay_max_port: 65535
  strict_expiry: "false"
  relay_ipv4_addr: 15.235.118.34
  listen:
    - transport: udp
      ip: '::'
      port: 3478
    - transport: tcp
      ip: '::'
      port: 3478
  log_level: info
  log_dir: /logs/
  blacklist:
    - 127.0.0.0/8
    - ::1
