services:
  eturnal-app:
    image: tiredofit/eturnal:latest
    container_name: eturnal-app
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 50000-50500:50000-50500/udp
    volumes:
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=eturnal-app
      - CONTAINER_ENABLE_MONITORING=FALSE
      - SETUP_TYPE=AUTO

      - SOFTWARE_NAME=eturnal
      - REALM=example.com
      - ENABLE_IPV4=TRUE
      - PUBLIC_IPV4=auto

      - RELAY_MIN_PORT=50000
      - RELAY_MAX_PORT=50500

      - LOG_LEVEL=info
    networks:
      - services
    restart: always

networks:
  services:
    external: true
