services:
  eturnal-app:
    image: tiredofit/eturnal:latest
    container_name: eturnal-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.eturnal.rule=Host(`eturnal.example.com`)
      - traefik.http.services.eturnal.loadbalancer.server.port=80
    volumes:
      - ./config:/config
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=eturnal-app
      - SETUP_TYPE=AUTO
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
